kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node:16.13.0
  commands:
  - npm install --registry=https://registry.npm.taobao.org
  - npm run build
- name: deploy-dev
  image: appleboy/drone-scp
  settings:
    host: bt.rgs.chper.cn
    username: root
    password:
      from_secret: ssh_password
    target: /home/team/Docker/baota/site/pre.rgs.chper.cn
    source: dist/*
