kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
- name: git-pull
  image: appleboy/drone-ssh
  settings:
    host: bt.rgs.chper.cn
    username: root
    password:
      from_secret: ssh_password
    script:
      - cd /home/team/Docker/baota/site/pre.rgs.chper.cn/reveal.js
      - git pull